package com.raja.controller;

import java.security.Principal;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.raja.model.User;
import com.raja.model.UserRequest;
import com.raja.model.UserResponse;
import com.raja.service.IUserService;
import com.raja.util.JwtUtil;

@RestController
@RequestMapping("/user")
public class UserRestController {

	@Autowired
	private IUserService service;
	
	@Autowired
	private JwtUtil util;
	
	@Autowired
	private AuthenticationManager authenticationManager;
	
	//1. Save User data in database
	@PostMapping("/save")
	public ResponseEntity<String> saveUser(@RequestBody User user) {
		
		Integer id = service.saveUser(user);
		String body = "User '"+id+"' saved";
		return new ResponseEntity<>(body,HttpStatus.OK);
	}
	
	//2. Validate user and generate token(login)
	@PostMapping("/login")
	public ResponseEntity<UserResponse> loginUser(@RequestBody UserRequest request){
		//  Validate username/Password with database
		authenticationManager.authenticate(
				new UsernamePasswordAuthenticationToken(
				request.getUsername(), request.getPassword()));
		
		String token = util.generateToken(request.getUsername()); 
		return ResponseEntity.ok(
				new UserResponse(token,"SUCCESS ! Generated by RAJA"));
	}
	
	//3. after login only
	@PostMapping("/welcome")
	public ResponseEntity<String> accessData(Principal p){
		return ResponseEntity.ok("HELLO USER-----"+ p.getName());
	}
}
